/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

/**
 *
 * @author Jesus Marcelo
 */
public class Cursos extends javax.swing.JPanel {

    /**
     * Creates new form Cursos
     */
    public Cursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        curso10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        curso1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        curso4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        curso7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        curso13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        curso11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        curso2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        curso5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        curso8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        curso14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        curso12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        curso3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        curso6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        curso9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        curso15 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 420));

        jPanel1.setBackground(new java.awt.Color(236, 167, 57));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 420));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        curso10.setBackground(new java.awt.Color(244, 168, 93));
        curso10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel2.setText("HIST. DEL PERÚ");
        curso10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel3.setText("-");
        curso10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 50));

        curso1.setBackground(new java.awt.Color(244, 168, 93));
        curso1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel4.setText("RAZON. VERBAL");
        curso1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel5.setText("-");
        curso1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 50));

        curso4.setBackground(new java.awt.Color(244, 168, 93));
        curso4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel6.setText("LITERATURA");
        curso4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel7.setText("-");
        curso4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 50));

        curso7.setBackground(new java.awt.Color(244, 168, 93));
        curso7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel8.setText("LENGUAJE");
        curso7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel9.setText("-");
        curso7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 50));

        curso13.setBackground(new java.awt.Color(244, 168, 93));
        curso13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel10.setText("HIST. UNIVERSAL");
        curso13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel11.setText("-");
        curso13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 50));

        curso11.setBackground(new java.awt.Color(244, 168, 93));
        curso11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        curso11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel13.setText("-");
        curso11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, 50));

        curso2.setBackground(new java.awt.Color(244, 168, 93));
        curso2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel14.setText("FÍSICA 2");
        curso2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel15.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel15.setText("-");
        curso2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, 50));

        curso5.setBackground(new java.awt.Color(244, 168, 93));
        curso5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel16.setText("QUÍMICA");
        curso5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel17.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel17.setText("-");
        curso5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, 50));

        curso8.setBackground(new java.awt.Color(244, 168, 93));
        curso8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel18.setText("BIOLOGÍA");
        curso8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel19.setText("-");
        curso8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, 50));

        curso14.setBackground(new java.awt.Color(244, 168, 93));
        curso14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        curso14.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel21.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel21.setText("-");
        curso14.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, 50));

        curso12.setBackground(new java.awt.Color(244, 168, 93));
        curso12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel22.setText("ÁLGEBRA");
        curso12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel23.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel23.setText("-");
        curso12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, 50));

        curso3.setBackground(new java.awt.Color(244, 168, 93));
        curso3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel24.setText("ARITMÉTICA");
        curso3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel25.setText("-");
        curso3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 50));

        curso6.setBackground(new java.awt.Color(244, 168, 93));
        curso6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel26.setText("TRIGONOMETRÍA");
        curso6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel27.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel27.setText("-");
        curso6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, -1, 50));

        curso9.setBackground(new java.awt.Color(244, 168, 93));
        curso9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel28.setText("GEOMETRÍA");
        curso9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel29.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel29.setText("-");
        curso9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, 50));

        curso15.setBackground(new java.awt.Color(244, 168, 93));
        curso15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel30.setText("RAZON. MATEMATICO");
        curso15.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 15, 277, -1));

        jLabel31.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel31.setText("-");
        curso15.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 28, -1));

        jPanel1.add(curso15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel curso1;
    private javax.swing.JPanel curso10;
    private javax.swing.JPanel curso11;
    private javax.swing.JPanel curso12;
    private javax.swing.JPanel curso13;
    private javax.swing.JPanel curso14;
    private javax.swing.JPanel curso15;
    private javax.swing.JPanel curso2;
    private javax.swing.JPanel curso3;
    private javax.swing.JPanel curso4;
    private javax.swing.JPanel curso5;
    private javax.swing.JPanel curso6;
    private javax.swing.JPanel curso7;
    private javax.swing.JPanel curso8;
    private javax.swing.JPanel curso9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
